In [1]:
import math
import numpy as np
import pandas as pd

In [2]:
#读取数据
data = pd.read_excel('附件.xlsx')
data.head()

x坐标 (m)  y坐标 (m)
0  107.250   11.664
1  105.360   23.191
2  102.235   34.447
3   97.911   45.299
4   92.440   55.619

In [4]:
# 将数据转化为矩阵
data = np.array(data)
data

array([[107.25 ,  11.664],
       [105.36 ,  23.191],
       [102.235,  34.447],
       ...,
       [334.636, -40.95 ],
       [336.233, -24.609],
       [337.032,  -8.21 ]])

In [11]:
# 计算每个样本的曼哈顿距离
def manhattan_distance(P1, P2):
    return np.sum(abs(P1 - P2))

# 创建result矩阵，用于存放每个样本之间的曼哈顿距离
result = np.zeros((len(data), len(data)))
for i in range(len(data)):
    for j in range(len(data)):
        if i < j:
            result[i][j] = manhattan_distance(data[i], data[j])
        else:
            result[i][j] = 0
result

array([[  0.   , 199.056, 184.675, ..., 492.473, 477.729, 462.129],
       [  0.   ,   0.   ,  14.381, ..., 293.417, 278.673, 263.073],
       [  0.   ,   0.   ,   0.   , ..., 307.798, 293.054, 277.454],
       ...,
       [  0.   ,   0.   ,   0.   , ...,   0.   ,  17.938,  35.136],
       [  0.   ,   0.   ,   0.   , ...,   0.   ,   0.   ,  17.198],
       [  0.   ,   0.   ,   0.   , ...,   0.   ,   0.   ,   0.   ]])

In [16]:
# 计算每个样本的欧式
def distance(P1, P2):
    return np.sqrt(np.sum((P1 - P2) ** 2))

# 创建result矩阵，用于存放每个样本之间的距离
result = np.zeros((len(data), len(data)))
for i in range(len(data)):
    for j in range(len(data)):
        if i < j:
            result[i][j] = distance(data[i], data[j])
        else:
            result[i][j] = 0
result

array([[  0.        , 140.99528367, 131.3329693 , ..., 369.99158242,
        364.79274706, 359.49941368],
       [  0.        ,   0.        ,  11.68174478, ..., 238.07887781,
        235.76934094, 233.79037274],
       [  0.        ,   0.        ,   0.        , ..., 244.3254641 ,
        241.3351925 , 238.64042168],
       ...,
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
         16.41885167,  32.82755574],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,  16.41845309],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ]])

In [14]:
distance = result
def judge(distance):

最大距离为： 674.214986883264
