In [1]:
from GroundProjection import *
from IntersectArea import *
from ColumnProjection import *
from shapely.geometry import Polygon
import numpy as np


In [2]:
print(GroundProjection(np.array([1,2,3]),np.array([-1,-3,-4])))

[1.75 0.   6.  ]


In [2]:
vector = np.array([200,0,76])
points = np.array([[-197.4,3,2.5],[-197.4,-3,2.5],[-202.60,3,5.5],[-202.60,-3,5.5]])
print(ColumnProjection(vector,points))

a
[[   0.       3.      77.512]
 [-197.4     -3.       2.5  ]
 [-202.6      3.       5.5  ]
 [-202.6     -3.       5.5  ]]
[[   0.       3.      77.512]
 [   0.      -3.      77.512]
 [-202.6      3.       5.5  ]
 [-202.6     -3.       5.5  ]]
[[ 0.00000000e+00  3.00000000e+00  7.75120000e+01]
 [ 0.00000000e+00 -3.00000000e+00  7.75120000e+01]
 [-2.84217094e-14  3.00000000e+00  8.24880000e+01]
 [-2.02600000e+02 -3.00000000e+00  5.50000000e+00]]
[[ 0.00000000e+00  3.00000000e+00  7.75120000e+01]
 [ 0.00000000e+00 -3.00000000e+00  7.75120000e+01]
 [-2.84217094e-14  3.00000000e+00  8.24880000e+01]
 [-2.84217094e-14 -3.00000000e+00  8.24880000e+01]]
[[ 3.00000000e+00  0.00000000e+00  7.75120000e+01]
 [-3.00000000e+00  0.00000000e+00  7.75120000e+01]
 [ 3.00000000e+00  2.84217094e-14  8.24880000e+01]
 [-3.00000000e+00  2.84217094e-14  8.24880000e+01]]


In [ ]:
def ever_mirror():
    '''
        输入时间
    '''