In [1]:
from GroundProjection import *
from IntersectArea import *
from ColumnProjection import *
import numpy as np


In [2]:
print(GroundProjection(np.array([1,2,3]),np.array([-1,-3,-4])))

[1.75 0.   6.  ]


In [2]:
vector = np.array([200,0,76])
points = np.array([[-197.4,3,2.5],[-197.4,-3,2.5],[-202.60,3,5.5],[-202.60,-3,5.5]])
print(ColumnProjection(vector,points))

a
[-197.4    3.     2.5]
[-197.4   -3.     2.5]
[-202.6    3.     5.5]
[-202.6   -3.     5.5]
[[  3.  197.4   2.5]
 [ -3.  197.4   2.5]
 [  3.  202.6   5.5]
 [ -3.  202.6   5.5]]
