In [1]:
from GroundProjection import *
from IntersectArea import *
from ColumnProjection import *
# from shapely.geometry import Polygon

from 求太阳各角度 import *
from 阳光向量 import *
from 求镜面顶点 import *
from 求镜面法向量 import *

from judge import *  # 读取距离矩阵并分析

import numpy as np
import pandas as pd


In [13]:
# 函数测试
print(GroundProjection(np.array([1,2,3]),np.array([-1,-3,-4])))
print(IntersectArea([[1,1],[2,1],[2,3],[1,3]],[[1,2],[1.5,1],[3,4],[2,4]]))
vector = np.array([200,0,76])
points = np.array([[-197.4,3,2.5],[-197.4,-3,2.5],[-202.60,-3,5.5],[-202.60,3,5.5]])
print(ColumnProjection(vector,points)[:,[0,2]])

a
[[   0.       3.      77.512]
 [-197.4     -3.       2.5  ]
 [-202.6     -3.       5.5  ]
 [-202.6      3.       5.5  ]]
[[   0.       3.      77.512]
 [   0.      -3.      77.512]
 [-202.6     -3.       5.5  ]
 [-202.6      3.       5.5  ]]
[[ 0.00000000e+00  3.00000000e+00  7.75120000e+01]
 [ 0.00000000e+00 -3.00000000e+00  7.75120000e+01]
 [-2.84217094e-14 -3.00000000e+00  8.24880000e+01]
 [-2.02600000e+02  3.00000000e+00  5.50000000e+00]]
[[ 0.00000000e+00  3.00000000e+00  7.75120000e+01]
 [ 0.00000000e+00 -3.00000000e+00  7.75120000e+01]
 [-2.84217094e-14 -3.00000000e+00  8.24880000e+01]
 [-2.84217094e-14  3.00000000e+00  8.24880000e+01]]
[[ 3.    77.512]
 [-3.    77.512]
 [-3.    82.488]
 [ 3.    82.488]]


In [ ]:
# 距离矩阵计算

#读取数据
data = pd.read_excel('附件.xlsx')
data = np.array(data)

# 计算每个样本的欧式
def distance(P1, P2):
    return np.sqrt(np.sum((P1 - P2) ** 2))

# 创建result矩阵，用于存放每个样本之间的距离
result = np.zeros((len(data), len(data)))
for i in range(len(data)):
    for j in range(len(data)):
        if i < j:
            result[i][j] = distance(data[i], data[j])
        else:
            result[i][j] = 0
# 把上三角矩阵result转化为对称矩阵
for i in range(len(data)):
    for j in range(len(data)):
        if i > j:
            result[i][j] = result[j][i]